      INTEGER AMOUNT,BIGS,INITIL,INVLEV,NEVNTS,NEXT,NMNTHS,NVALUE,
     &        SMALLS
      REAL AMINUS,APLUS,H,INCRMC,MAXLAG,MDEMDT,MINLAG,PI,PROBD(25),
     &     SETUPC,TIME,TLEVNT,TNE(4),TORDC
      INTEGER IRANDI
      REAL EXPON,UNIFRM
      COMMON /MODEL/ AMINUS,AMOUNT,APLUS,BIGS,H,INCRMC,INITIL,INVLEV,
     &               MAXLAG,MDEMDT,MINLAG,NEVNTS,NEXT,NMNTHS,NVALUE,PI,
     &               PROBD,SETUPC,SMALLS,TIME,TLEVNT,TNE,TORDC
 
