      INTEGER QLIMIT
      PARAMETER (QLIMIT = 100)
      INTEGER BUSY,IDLE,NEVNTS,NEXT,NIQ,NUMCUS,SERVER,TOTCUS
      REAL ANIQ,AUTIL,MARRVT,MSERVT,TARRVL(QLIMIT),TIME,TLEVNT,TNE(2),
     &     TOTDEL
      REAL EXPON
      COMMON /MODEL/ ANIQ,AUTIL,BUSY,IDLE,MARRVT,MSERVT,NEVNTS,NEXT,NIQ,
     &               NUMCUS,SERVER,TARRVL,TIME,TLEVNT,TNE,TOTCUS,TOTDEL

