      INTEGER QLIMIT
      PARAMETER (QLIMIT = 100)
      INTEGER BUSY,IDLE,NEVNTS,NEXT,NIQ,NUMCUS,SERVER
      REAL ANIQ,AUTIL,MARRVT,MSERVT,TARRVL(QLIMIT),TEND,TIME,TLEVNT,
     &     TNE(3),TOTDEL
      REAL EXPON
      COMMON /MODEL/ ANIQ,AUTIL,BUSY,IDLE,MARRVT,MSERVT,NEVNTS,NEXT,NIQ,
     &               NUMCUS,SERVER,TARRVL,TEND,TIME,TLEVNT,TNE,TOTDEL
